/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ConnectRouteImport } from "./routes/connect";
import { Route as ContactRouteImport } from "./routes/contact";
import { Route as LegalRouteImport } from "./routes/legal";
import { Route as OldRouteRouteImport } from "./routes/old/route";
import { Route as ProjectsRouteRouteImport } from "./routes/projects/route";
import { Route as MarketingSitesHgmPrivacyRouteImport } from "./routes/marketing-sites/hgm-privacy";
import { Route as OldIndexRouteImport } from "./routes/old/index";
import { Route as ProjectsIndexRouteImport } from "./routes/projects/index";
import { Route as ProjectsPRouteRouteImport } from "./routes/projects/p/route";
import { Route as RSlugRouteImport } from "./routes/r/$slug";
import { Route as ProjectsPHackgwinnettWebRouteImport } from "./routes/projects/p/hackgwinnett-web";
import { Route as ProjectsPNotionCmsDemoRouteImport } from "./routes/projects/p/notion-cms-demo";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ConnectRoute = ConnectRouteImport.update({
  id: "/connect",
  path: "/connect",
  getParentRoute: () => rootRouteImport,
} as any);
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any);
const LegalRoute = LegalRouteImport.update({
  id: "/legal",
  path: "/legal",
  getParentRoute: () => rootRouteImport,
} as any);
const OldRouteRoute = OldRouteRouteImport.update({
  id: "/old",
  path: "/old",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const MarketingSitesHgmPrivacyRoute = MarketingSitesHgmPrivacyRouteImport.update({
  id: "/marketing-sites/hgm-privacy",
  path: "/marketing-sites/hgm-privacy",
  getParentRoute: () => rootRouteImport,
} as any);
const OldIndexRoute = OldIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OldRouteRoute,
} as any);
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ProjectsRouteRoute,
} as any);
const ProjectsPRouteRoute = ProjectsPRouteRouteImport.update({
  id: "/p",
  path: "/p",
  getParentRoute: () => ProjectsRouteRoute,
} as any);
const RSlugRoute = RSlugRouteImport.update({
  id: "/r/$slug",
  path: "/r/$slug",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsPHackgwinnettWebRoute = ProjectsPHackgwinnettWebRouteImport.update({
  id: "/hackgwinnett-web",
  path: "/hackgwinnett-web",
  getParentRoute: () => ProjectsPRouteRoute,
} as any);
const ProjectsPNotionCmsDemoRoute = ProjectsPNotionCmsDemoRouteImport.update({
  id: "/notion-cms-demo",
  path: "/notion-cms-demo",
  getParentRoute: () => ProjectsPRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/old": typeof OldRouteRouteWithChildren;
  "/projects": typeof ProjectsRouteRouteWithChildren;
  "/connect": typeof ConnectRoute;
  "/contact": typeof ContactRoute;
  "/legal": typeof LegalRoute;
  "/projects/p": typeof ProjectsPRouteRouteWithChildren;
  "/marketing-sites/hgm-privacy": typeof MarketingSitesHgmPrivacyRoute;
  "/r/$slug": typeof RSlugRoute;
  "/old/": typeof OldIndexRoute;
  "/projects/": typeof ProjectsIndexRoute;
  "/projects/p/hackgwinnett-web": typeof ProjectsPHackgwinnettWebRoute;
  "/projects/p/notion-cms-demo": typeof ProjectsPNotionCmsDemoRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/connect": typeof ConnectRoute;
  "/contact": typeof ContactRoute;
  "/legal": typeof LegalRoute;
  "/projects/p": typeof ProjectsPRouteRouteWithChildren;
  "/marketing-sites/hgm-privacy": typeof MarketingSitesHgmPrivacyRoute;
  "/r/$slug": typeof RSlugRoute;
  "/old": typeof OldIndexRoute;
  "/projects": typeof ProjectsIndexRoute;
  "/projects/p/hackgwinnett-web": typeof ProjectsPHackgwinnettWebRoute;
  "/projects/p/notion-cms-demo": typeof ProjectsPNotionCmsDemoRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/old": typeof OldRouteRouteWithChildren;
  "/projects": typeof ProjectsRouteRouteWithChildren;
  "/connect": typeof ConnectRoute;
  "/contact": typeof ContactRoute;
  "/legal": typeof LegalRoute;
  "/projects/p": typeof ProjectsPRouteRouteWithChildren;
  "/marketing-sites/hgm-privacy": typeof MarketingSitesHgmPrivacyRoute;
  "/r/$slug": typeof RSlugRoute;
  "/old/": typeof OldIndexRoute;
  "/projects/": typeof ProjectsIndexRoute;
  "/projects/p/hackgwinnett-web": typeof ProjectsPHackgwinnettWebRoute;
  "/projects/p/notion-cms-demo": typeof ProjectsPNotionCmsDemoRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/old"
    | "/projects"
    | "/connect"
    | "/contact"
    | "/legal"
    | "/projects/p"
    | "/marketing-sites/hgm-privacy"
    | "/r/$slug"
    | "/old/"
    | "/projects/"
    | "/projects/p/hackgwinnett-web"
    | "/projects/p/notion-cms-demo";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/connect"
    | "/contact"
    | "/legal"
    | "/projects/p"
    | "/marketing-sites/hgm-privacy"
    | "/r/$slug"
    | "/old"
    | "/projects"
    | "/projects/p/hackgwinnett-web"
    | "/projects/p/notion-cms-demo";
  id:
    | "__root__"
    | "/"
    | "/old"
    | "/projects"
    | "/connect"
    | "/contact"
    | "/legal"
    | "/projects/p"
    | "/marketing-sites/hgm-privacy"
    | "/r/$slug"
    | "/old/"
    | "/projects/"
    | "/projects/p/hackgwinnett-web"
    | "/projects/p/notion-cms-demo";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  OldRouteRoute: typeof OldRouteRouteWithChildren;
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren;
  ConnectRoute: typeof ConnectRoute;
  ContactRoute: typeof ContactRoute;
  LegalRoute: typeof LegalRoute;
  MarketingSitesHgmPrivacyRoute: typeof MarketingSitesHgmPrivacyRoute;
  RSlugRoute: typeof RSlugRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/connect": {
      id: "/connect";
      path: "/connect";
      fullPath: "/connect";
      preLoaderRoute: typeof ConnectRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/legal": {
      id: "/legal";
      path: "/legal";
      fullPath: "/legal";
      preLoaderRoute: typeof LegalRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/old": {
      id: "/old";
      path: "/old";
      fullPath: "/old";
      preLoaderRoute: typeof OldRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof ProjectsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/marketing-sites/hgm-privacy": {
      id: "/marketing-sites/hgm-privacy";
      path: "/marketing-sites/hgm-privacy";
      fullPath: "/marketing-sites/hgm-privacy";
      preLoaderRoute: typeof MarketingSitesHgmPrivacyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/old/": {
      id: "/old/";
      path: "/";
      fullPath: "/old/";
      preLoaderRoute: typeof OldIndexRouteImport;
      parentRoute: typeof OldRouteRoute;
    };
    "/projects/": {
      id: "/projects/";
      path: "/";
      fullPath: "/projects/";
      preLoaderRoute: typeof ProjectsIndexRouteImport;
      parentRoute: typeof ProjectsRouteRoute;
    };
    "/projects/p": {
      id: "/projects/p";
      path: "/p";
      fullPath: "/projects/p";
      preLoaderRoute: typeof ProjectsPRouteRouteImport;
      parentRoute: typeof ProjectsRouteRoute;
    };
    "/r/$slug": {
      id: "/r/$slug";
      path: "/r/$slug";
      fullPath: "/r/$slug";
      preLoaderRoute: typeof RSlugRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/p/hackgwinnett-web": {
      id: "/projects/p/hackgwinnett-web";
      path: "/hackgwinnett-web";
      fullPath: "/projects/p/hackgwinnett-web";
      preLoaderRoute: typeof ProjectsPHackgwinnettWebRouteImport;
      parentRoute: typeof ProjectsPRouteRoute;
    };
    "/projects/p/notion-cms-demo": {
      id: "/projects/p/notion-cms-demo";
      path: "/notion-cms-demo";
      fullPath: "/projects/p/notion-cms-demo";
      preLoaderRoute: typeof ProjectsPNotionCmsDemoRouteImport;
      parentRoute: typeof ProjectsPRouteRoute;
    };
  }
}

interface OldRouteRouteChildren {
  OldIndexRoute: typeof OldIndexRoute;
}

const OldRouteRouteChildren: OldRouteRouteChildren = {
  OldIndexRoute: OldIndexRoute,
};

const OldRouteRouteWithChildren = OldRouteRoute._addFileChildren(OldRouteRouteChildren);

interface ProjectsPRouteRouteChildren {
  ProjectsPHackgwinnettWebRoute: typeof ProjectsPHackgwinnettWebRoute;
  ProjectsPNotionCmsDemoRoute: typeof ProjectsPNotionCmsDemoRoute;
}

const ProjectsPRouteRouteChildren: ProjectsPRouteRouteChildren = {
  ProjectsPHackgwinnettWebRoute: ProjectsPHackgwinnettWebRoute,
  ProjectsPNotionCmsDemoRoute: ProjectsPNotionCmsDemoRoute,
};

const ProjectsPRouteRouteWithChildren = ProjectsPRouteRoute._addFileChildren(
  ProjectsPRouteRouteChildren,
);

interface ProjectsRouteRouteChildren {
  ProjectsPRouteRoute: typeof ProjectsPRouteRouteWithChildren;
  ProjectsIndexRoute: typeof ProjectsIndexRoute;
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsPRouteRoute: ProjectsPRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
};

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OldRouteRoute: OldRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  LegalRoute: LegalRoute,
  MarketingSitesHgmPrivacyRoute: MarketingSitesHgmPrivacyRoute,
  RSlugRoute: RSlugRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
